### ISSUE TITLE
Sissi - Create back-end endpoint for getting to-do list

### ISSUE THREAD

**Issue by codingzilin** [Ben0189/Blotz-Task-App#34]
- [ ] Create a .NET project
- [ ] Create a API to get to-do list TaskDTO
- [ ] Setup SQL server

Example details:
export interface TaskDTO{
    id: number;
    name: string;
    description: string;
    dueDate: Date;
    status: string;
    priority: string;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date;
}
